[package]
name = "celo_web3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.18.0"
ethers = "2.0.0"
tokio = "1.26.0"
